Goal Detail Accordion updated and conflicts fixed
zurichat/zc_plugin_company_goals pull request #1136
Opened 2021-10-02 17:27 UTC by Ariiieee

updated files and conflicts fixed

2021-10-02 19:22 UTC, abiona01 commented
@tundealabi review

2021-10-03 08:43 UTC, Adeniyii requested changes
Hi, there are merge highlights all over your code, please review, thanks.

2021-10-03 08:43 UTC, Adeniyii commented on package.json
> +<<<<<<< HEAD
here

2021-10-03 08:43 UTC, Adeniyii commented on package.json
> +=======
here

2021-10-03 08:43 UTC, Adeniyii commented on package.json
> +>>>>>>> 1d17d85f3d15f3bef32b4d15a35c8ef48d935a0e
here

2021-10-03 08:43 UTC, Adeniyii commented on client/yarn.lock
> +<<<<<<< HEAD
here

2021-10-03 08:43 UTC, Adeniyii commented on yarn.lock
> +>>>>>>> 1d17d85f3d15f3bef32b4d15a35c8ef48d935a0e
here

2021-10-04 19:31 UTC, closed without merging