Feat: Sidebar controller & route
zurichat/zc_plugin_company_goals pull request #338
Opened 2021-08-31 19:58 UTC by adepeju4

For now, i filled the sidebar data with dummy texts so i could quickly set up the routing.

2021-08-31 20:14 UTC, Asylcreek requested changes

2021-08-31 20:14 UTC, Asylcreek commented on controllers/sidebarController.js
> +  await Promise.resolve('Read sidebar');
So, you might not need this line. I only put it the goalControllers file to show what the catchAsync wrapper does.

2021-08-31 20:14 UTC, Asylcreek commented on app.js
> +app.use('/sidebar', rateLimiter(), sidebarRouter);
Please change "/sidebar" to "/api/v1/sidebar". Because we are serving the frontend static files, prefixing the api routes with "/api/v1" should help us prevent clashes

2021-08-31 20:14 UTC, Asylcreek commented on controllers/sidebarController.js
> +  return res.status(200).json(sidebarOptions).end();
You might not need the .end(). The calling res ends the response cycle already

2021-08-31 20:16 UTC, adepeju4 commented on controllers/sidebarController.js
> +  await Promise.resolve('Read sidebar');
oh well, i thought you guys had a template / uniformity you'd want the controllers to follow? hence why i added it.

2021-08-31 20:21 UTC, Asylcreek commented on controllers/sidebarController.js
> +  await Promise.resolve('Read sidebar');
Don't mind me joor. I understand. Can you please remove the line? To hopefully help others not add the line in the future

2021-08-31 20:26 UTC, adepeju4 commented on app.js
> +app.use('/sidebar', rateLimiter(), sidebarRouter);
hmmm alright.

2021-08-31 20:26 UTC, adepeju4 commented on controllers/sidebarController.js
> +  return res.status(200).json(sidebarOptions).end();
i thought only res.send() does that? thanks for the insight.

2021-08-31 20:31 UTC, adepeju4 commented
close #326

2021-08-31 20:34 UTC, Asylcreek requested changes

2021-08-31 20:34 UTC, Asylcreek commented on controllers/sidebarController.js
> +const readSidebar = catchAsync(async (req, res) => {
I am so sorry for not mentioning this earlier. You might not even need the catchAsync wrapper because there isn't any async code in there.

2021-08-31 20:38 UTC, Ajioz commented on controllers/sidebarController.js
> +  return res.status(200).json(sidebarOptions).end();
Also since we need it to be much more stateful we need the route to check the structure of the output and set the header information accordingly, which the .end() removes

2021-08-31 20:42 UTC, adepeju4 commented on controllers/sidebarController.js
> +  return res.status(200).json(sidebarOptions).end();
oh interesting. source?

2021-08-31 20:42 UTC, Asylcreek commented
[image: image.png]

On Tue, Aug 31, 2021 at 9:38 PM Sunday Ajiroghene ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In controllers/sidebarController.js
> <https://github.com/zurichat/zc_plugin_company_goals/pull/338#discussion_r699656710>
> :
>
> > @@ -0,0 +1,11 @@
> +/* eslint-disable no-console */
> +const sidebarOptions = require('../data/sidebarData.json');
> +
> +const catchAsync = require('../utils/catchAsync');
> +
> +const readSidebar = catchAsync(async (req, res) => {
> +  await Promise.resolve('Read sidebar');
> +  return res.status(200).json(sidebarOptions).end();
>
> Also since we need it to be much more stateful we need the route to check
> the structure of the output and set the header information accordingly,
> which the .end() removes
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zurichat/zc_plugin_company_goals/pull/338#discussion_r699656710>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM6NOVLQRDJC7XNPMMLTC6DT7U4UZANCNFSM5DE3VDMQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-08-31 20:47 UTC, adepeju4 commented on controllers/sidebarController.js
> +const readSidebar = catchAsync(async (req, res) => {
cool, but i'm curious why you'd put in a code that literally does nothing for your route.

2021-08-31 21:02 UTC, Asylcreek commented on controllers/sidebarController.js
> +const readSidebar = catchAsync(async (req, res) => {
I felt I had to show an example of catchAsync being used, because some people tend to not go throught the list of available files before writing code.

2021-08-31 21:13 UTC, merged

2021-09-02 12:56 UTC, adepeju4 commented
close #326

2021-09-03 13:31 UTC, adepeju4 commented
I have filled the sidebar details with the correct data :)