Staging
zurichat/zc_plugin_company_goals pull request #339
Opened 2021-08-31 21:04 UTC by Adeniyii

- The info JSON response has the correct fields, but is filled with dummy data for now.
- Changes will be made accordingly.

2021-08-31 21:09 UTC, Asylcreek requested changes

2021-08-31 21:09 UTC, Asylcreek commented on routes/infoRoute.js
> +const getPluginInfo = (req, res) => {
Please extract this function into a controller

2021-08-31 21:10 UTC, Adeniyii commented on routes/infoRoute.js
> +const getPluginInfo = (req, res) => {
I'm on it.

2021-08-31 21:29 UTC, Asylcreek commented
Alright then. Please pull from the staging branch and push again. It seems like you are a commit behind

2021-08-31 21:58 UTC, merged

2021-09-01 17:33 UTC, Adeniyii commented
close #329