feat: created updateGoalByID controller
zurichat/zc_plugin_company_goals pull request #460
Opened 2021-09-03 16:11 UTC by devteni

To test: https://goals.zuri.chat/api/v1/update/612e42849f34172f0cac4026
issue #335

2021-09-03 21:43 UTC, Asylcreek commented
Please pull from the staging branch, and resolve the conflicts then make the PR again

2021-09-04 08:37 UTC, devteni commented on routes/goalRoutes.js
> +router.route("/:id").patch(updateGoalByID);
That's making a get request boss. And it's not my modification

2021-09-04 08:47 UTC, Asylcreek commented on routes/goalRoutes.js
> +router.route("/:id").patch(updateGoalByID);
I am not asking to modify the implementation.

I am asking you to chain yours to the route.

Like so `router.route('/:id').get(getSingleGoal).patch(updateGoalByID)`

2021-09-04 08:58 UTC, devteni commented on routes/goalRoutes.js
> +router.route("/:id").patch(updateGoalByID);
Okay, a minute

2021-09-04 09:00 UTC, devteni commented on routes/goalRoutes.js
> +router.route("/:id").patch(updateGoalByID);
Done

2021-09-04 09:03 UTC, Asylcreek requested changes

2021-09-04 09:03 UTC, Asylcreek commented on routes/goalRoutes.js
>  router.route('/:id').get(getSingleGoal);
You can remove this line now.

Line 14 has the implementation

2021-09-04 09:37 UTC, devteni commented on routes/goalRoutes.js
>  router.route('/:id').get(getSingleGoal);
Done

2021-09-04 10:11 UTC, Asylcreek commented
Just one more thing, please pull from the staging branch, resolve them conflicts then push to your repo again

2021-09-04 12:15 UTC, Asylcreek commented
Just another thing, please pull from the staging branch, resolve them conflicts then push to your repo again

2021-09-04 16:48 UTC, merged