Created a GET request to get mission
zurichat/zc_plugin_company_goals pull request #465
Opened 2021-09-03 17:38 UTC by Celnet-hub

2021-09-03 21:31 UTC, Asylcreek requested changes

2021-09-03 21:31 UTC, Asylcreek commented on app.js
> +const sidebarRouter = require('./routes/sidebarRoute.js');
Please remove one of these

2021-09-03 21:31 UTC, Asylcreek commented on app.js
> +app.use('/get_mission', missionRouter);
Please change 'get_mission' to 'get-mission'

2021-09-03 21:34 UTC, Celnet-hub commented on app.js
> +const sidebarRouter = require('./routes/sidebarRoute.js');
That's why it was comments. I don't know what did that

2021-09-03 22:09 UTC, Celnet-hub commented on app.js
> +app.use('/get_mission', missionRouter);
Done

2021-09-03 22:11 UTC, merged

2021-09-06 08:42 UTC, Celnet-hub commented
**Created a route to get the company's mission**

Click [link](https://goals.zuri.chat/api/mission/6135d087098aca7c1a5bc6a3) to test.