Get company goals
zurichat/zc_plugin_company_goals pull request #467
Opened 2021-09-03 17:48 UTC by chuksdozie

get company goals tab this resolves issues #349

2021-09-03 21:34 UTC, Asylcreek requested changes

2021-09-03 21:34 UTC, Asylcreek commented on .github/workflows/main.yml
> +>>>>>>> e0f09c91a6eae2595c80f7171b5bdbf24e444c68
This file is still in the merging state, please complete your local merging.

If you are not sure which side is correct, just pull from the staging branch

2021-09-04 03:41 UTC, chuksdozie commented on .github/workflows/main.yml
> +>>>>>>> e0f09c91a6eae2595c80f7171b5bdbf24e444c68
ok, this stuff is over whelming at times, the whole thing is always changing

2021-09-04 04:09 UTC, chuksdozie commented on .github/workflows/main.yml
> +>>>>>>> e0f09c91a6eae2595c80f7171b5bdbf24e444c68
please I am pulling and its saying it is up to date...

2021-09-04 04:14 UTC, chuksdozie commented on .github/workflows/main.yml
> +>>>>>>> e0f09c91a6eae2595c80f7171b5bdbf24e444c68
i have pulled this stuff over and over its saying its up to task and when i try to push its telling me to pull first

2021-09-04 04:18 UTC, chuksdozie commented
@Asylcreek I have fixed thw conflict please check

2021-09-04 07:53 UTC, Asylcreek requested changes

2021-09-04 07:53 UTC, Asylcreek commented on .github/workflows/main.yml
> +
Remove these lines, they are duplicates

2021-09-04 07:53 UTC, Asylcreek commented
There still is a conflict in the Home.jsx file

2021-09-04 08:51 UTC, chuksdozie commented
I dont even know what to do again. please what is the conflict?  @Asylcreek

2021-09-04 08:53 UTC, Asylcreek commented
Just go to the team's repo on Github. Find client/src/pages/Home.jsx. Copy the files, paste it in your local client/src/pages/Home.jsx. Then make the PR again

2021-09-04 08:55 UTC, chuksdozie commented
so I should close this one?

2021-09-04 08:57 UTC, Asylcreek commented
I don't think you have to. Just make the changes and push again

2021-09-04 09:22 UTC, Asylcreek requested changes

2021-09-04 09:22 UTC, Asylcreek commented on .github/workflows/main.yml
> +
This still needs to be worked on

2021-09-04 09:53 UTC, chuksdozie commented
@Asylcreek  please check now

2021-09-04 09:59 UTC, chuksdozie commented
@Asylcreek there are currently no conflicts

2021-09-04 10:09 UTC, abiona01 commented
He requested a change in file main.yml. You're yet to do so

2021-09-04 12:36 UTC, chuksdozie commented
> He requested a change in file main.yml. You're yet to do so

Sorry what are you talking about, the main.yml file is exactly what is on the staging branch like it was copy and paste @abiona01

2021-09-04 12:41 UTC, chuksdozie commented
@abiona01 please check o. There are no conflicts  currently..

2021-09-04 13:02 UTC, Asylcreek requested changes

2021-09-04 13:02 UTC, Asylcreek commented on .github/workflows/main.yml
> +
Please, go to the main.yml on our team's github page, copy the contents there and paste it into your local main.yml file.

2021-09-04 14:44 UTC, chuksdozie commented
please @abiona01  and @Asylcreek  I  want to draw your attention to the source of the conflict in the main.yml file, it is caused by the improper alignment on the part of the staging file..... where we have
`#    push`
`#        branches`

2021-09-04 16:04 UTC, chuksdozie commented
all the while I thought I was doing rubbish but the fact is that for every new PR that you merge, it automatically raises conflicts in everyones else PR because ofcourse they are no longer in sync with the staging branch again.

2021-09-04 18:34 UTC, chuksdozie commented
@abiona01 @Asylcreek  please check

2021-09-04 21:08 UTC, abiona01 approved these changes

2021-09-04 21:17 UTC, merged

2021-09-05 03:58 UTC, chuksdozie commented
this PR resolves issue #349 
the test link is right [here](https://goals.zuri.chat)