Add date input component
zurichat/zc_plugin_company_goals pull request #474
Opened 2021-09-03 18:56 UTC by hippiedev

Closes #302
I created a date input component and rendered it to the DOM.

To find it:

On goals.zuri.chat, click "open modal" (Green conspicuous button on the screen)
Scroll to "Date for goal completion", below you will see the input component for adding date.

2021-09-03 19:23 UTC, abiona01 requested changes

2021-09-03 19:23 UTC, abiona01 commented on client/src/components/createGoal/GoalForm.js
> -              />
Does the Placeholder still show Date after you deleted this block of code?

2021-09-04 05:01 UTC, Asylcreek commented
Hey so, you still have conflicts, pleaes pull from the staging branch, resolve them conflicts and make the PR again

2021-09-04 10:01 UTC, hippiedev commented on client/src/components/createGoal/GoalForm.js
> -              />
Yes, but that would take longer to do. But I will work on it.

2021-09-04 10:37 UTC, hippiedev commented
> Hey so, you still have conflicts, pleaes pull from the staging branch, resolve them conflicts and make the PR again

Conflicts resolved

2021-09-04 10:53 UTC, abiona01 commented
> > Hey so, you still have conflicts, pleaes pull from the staging branch, resolve them conflicts and make the PR again
> 
> Conflicts resolved

You're yet to answer my comment. Does the date input component display a placeholder like it does on the design? If it doesn't kindly revert the date input back to the way it was. Also, this will not pass for review. The whole createGoal component has been reviewed.

2021-09-04 11:12 UTC, hippiedev commented
> > > Hey so, you still have conflicts, pleaes pull from the staging branch, resolve them conflicts and make the PR again
> > 
> > 
> > Conflicts resolved
> 
> You're yet to answer my comment. Does the date input component display a placeholder like it does on the design? If it doesn't kindly revert the date input back to the way it was. Also, this will not pass for review. The whole createGoal component has been reviewed.

Okay

2021-09-04 11:19 UTC, closed without merging