Updated Delete Modal Design
zurichat/zc_plugin_company_goals pull request #494
Opened 2021-09-03 23:31 UTC by mowfaqqa

The image on the delete modal was changed therefore the new image was updated, and styled component was also implemented for styling the modal
modal created is in accordance with issues #402

2021-09-03 23:46 UTC, abiona01 requested changes

2021-09-03 23:46 UTC, abiona01 commented on client/src/components/mainside/Mainside.jsx
> -import Report from '../updates/Report'
Is there a specific reason you deleted this?

2021-09-03 23:46 UTC, abiona01 commented on client/src/pages/Home.jsx
> -        <Header />
The header component is deleted but it's imported in line 4. AppHeader is also imported, but isn't in the return statement

2021-09-03 23:46 UTC, abiona01 commented on client/src/index.css
>  }
Did you create this css file? All styling should be done with styled components. Read up on CreateGlobalStyles with styled components

2021-09-03 23:50 UTC, mowfaqqa commented on client/src/index.css
>  }
no its not me that created it

2021-09-03 23:51 UTC, mowfaqqa commented on client/src/components/mainside/Mainside.jsx
> -import Report from '../updates/Report'
it was showing twice which was giving me error

2021-09-03 23:53 UTC, mowfaqqa commented on client/src/pages/Home.jsx
> -        <Header />
that's how I initially pulled the code.. I wanted to adjust it but I decided not considering it might temper with certain codes

2021-09-03 23:56 UTC, abiona01 commented on client/src/pages/Home.jsx
> -        <Header />
Alright

2021-09-03 23:56 UTC, abiona01 commented on client/src/index.css
>  }
Alright

2021-09-04 00:02 UTC, abiona01 approved these changes

2021-09-04 00:09 UTC, abiona01 approved these changes

2021-09-04 05:03 UTC, merged

2021-09-04 07:19 UTC, mowfaqqa commented
Thanks